version: "3"

services:
  jupyter-lab:
    image: quay.io/jupyter/datascience-notebook:2024-02-24
    volumes:
      - .:/home/jovyan/
    ports:
      - 8888:8888
    command: >
      bash -c "pip install transformers tensorflow scikit-learn pandas numpy && jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password=''"
